version: "3.8"
services:
  mysql:
    image: mysql:5.7
    container_name: ${DB_CONTAINER}
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - .local/mysql5.7:/var/lib/mysql

