version: "3.8"
services:
  mysql:
    image: mysql:8.0
    platform: linux/x86_64
    container_name: ${DB_CONTAINER}
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - .local/mysql:/var/lib/mysql
